### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [DavydKod/person_struct_parser#1]
Student: Максімовіч Давид

Для прохідного:
:heavy_check_mark:  ! Brief Description:
✔️ ! Grammar Rules:
:heavy_check_mark: ! Core Files:
:heavy_check_mark:  ! CLI: я не бачу `credits information.`
:heavy_check_mark:  ! Project Name:
:heavy_check_mark:  ! Unit Tests:

Для мааксимального:
:x:   File System: потрібний запис у файл також, який визначає користувач
:heavy_check_mark:  Test Coverage: 
:heavy_check_mark: Error Handling: 
:heavy_check_mark:  cargo fmt:
✔️ cargo clippy: 
:heavy_check_mark:  makefile:
:x:  Completeness: автоматично зарахується після виконання всіх пунктів 
:heavy_check_mark:  Including a diagram or grammar in the Readme.md: оновиш після додаття нових правил
:heavy_check_mark:  Documentation:
✔️ Publishing: оновиш версію після всіх змін

✔️ Курсова може бути зарахована
Бал: 22/25

**Comment by DavydKod** [comment]
Вітання. Вніс нові фінальні зміни. Був би радий, якби Ви ще раз переглянули. Дякую)

**Comment by DavydKod** [comment]
Вітання. У останніх 3 комітах я виправив усі проблеми. Додав нові поля до структури, змінив граматику, замінив помилки своїми і додав вивід додаткової інфи при роботі із CLI. Чи могли б Ви ще раз перевірити, будь ласка? Дякую

**Comment by NYBACHOK** [comment]
Привіт. 
1. Я бачу ти маєш файл .pest, але навіть  не використовуєш крейт pest. Використай його і це тобі спростить написання. 
2. Правил то багато, але вони занадто просто. Ще 2 ментра не погоджуються, що пункт на 4 правила виконаний.  Коли я говорив про zip, то мав на увазі, що тобі потрібно парсити саме український zip, бо якщо мені не зраджує пам'ять, то в ньому обмежена навіть к-сть символів. 
3. Ти маєш використати thisserror у main, а не anyhow. 
```rust
 #[derive(Error, Debug)]
    pub enum MyError {
        ///Global error of parsing
        #[error("An error occurred: {0}")]
        SomeError(String)
    }


pub fn parse(string: &str) -> Result<Person, MyError> { ... }
```

**Comment by NYBACHOK** [comment]
Виправ саме проблему з нестачею правил

**Comment by DavydKod** [comment]
Гаразд. Зроблю парсинг тільки з укр zip, попробую використати pest і зміню і в main помилки своїми. Щодо правил. У мене парс виконується тільки тоді, коли заходить правило person, а якщо age, city і тд - ні. Якщо я зроблю, що виконуватиметься парсинг і при правилі name, age і тд окремо, то уже навіть більше 4 правил буде проходити, то пункт з 4 правилами виконається, так?

**Comment by NYBACHOK** [comment]
Мається на увазі, що саме 4 якихось складних правила, а не парсинг по якомусь правилу.
Приклад з іншої курсової, яка використовує peg
```rust
        pub rule hour() -> &'input str
            = $(hour:['0'..='1']? ['0'..='9'] ":" minute:['0'..='5']['0'..='9'] " " period:("am" / "pm"))
```

Це повноцінне правило. У твоєму випадку можна додати парс місця проживання

Якось по типу %країна > 3 символів з великої , місто з великої, 2 чи більше слова й у кінці має бути zip з у якому не більше 5 символів чи ще якесь правило.

**Comment by DavydKod** [comment]
Велике дякую! Ускладнив правила. Також змінив багато іншої логіки(хоча pest так і не використовував, бо не дуже хотів змінювати багато коду). Правила тепер тільки в ReadMe. Також змінив помилки своєю і тд. Був би вдячним якби Ви написали чи нормальні правила тепер:). Дякую

**Comment by NYBACHOK** [comment]
Ранку. Я оновив і поки займись пунктом запису в файл. Щодо правил поки не спіши.

**Comment by DavydKod** [comment]
Доброго ранку. Дякую. А що мається на увазі під записом у файл? Функція, що буде парсити вхідний рядок і записувати результат у файл?

**Comment by NYBACHOK** [comment]
> Доброго ранку. Дякую. А що мається на увазі під записом у файл? Функція, що буде парсити вхідний рядок і записувати результат у файл?

Так

**Comment by DavydKod** [comment]
Додав функцію запису у файл

**Comment by NYBACHOK** [comment]
1. Додай ще одне поле і правило до структури й з Grammar Rules буде закінчено
2. Ти маєш використати цю функцію у cli

Щодо запису у файл пару порад

```rust
    #[derive(Error, Debug)]
    pub enum MyError {
        ///File error
        #[error("An error occurred incorrect file: {0}")]
        IncorrectFile(#[from] std::io::Error),
}
```

```rust
let mut file =  File::create(file_path).map_err(MyError::IncorrectFile)?;
```

**Comment by NYBACHOK** [comment]
Ну і не забудь оновити + перевірити чи є cargo clippy і ти здав

**Comment by DavydKod** [comment]
Гаразд. Велике дякую!

**Comment by NYBACHOK** [comment]
Привіт. Напиши чи погоджуєшся з оцінкою

**Comment by DavydKod** [comment]
Вітання! Так, погоджуюсь. Дякую)
